/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.EquipeCtrl;
import control.GUIController;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Equipe;
import model.Projeto;
import model.Usuario;

/**
 *
 * @author Fabio
 */
public class EquipeView extends javax.swing.JFrame {
    private Usuario usuarioSessao;
    private GUIController guiController;
    private Projeto projeto;

    public Usuario getUsuarioSessao() {
        return usuarioSessao;
    }

    public void setUsuarioSessao(Usuario usuarioSessao) {
        this.usuarioSessao = usuarioSessao;
    }

    public Projeto getProjeto() {
        return projeto;
    }

    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }
    
    
    
    /**
     * Creates new form EquipeView
     * @param guiController
     * @param idProjeto
     */
    public EquipeView(GUIController guiController, Integer idProjeto) {
        this.guiController = guiController;
        
        guiController.setEquipeMembros(new ArrayList<>());
        projeto = new Projeto();
        projeto.setIdProjeto(idProjeto);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotAreaAtuacao = new javax.swing.JLabel();
        rotDescricao = new javax.swing.JLabel();
        rotFuncao = new javax.swing.JLabel();
        btEnviar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        cxAreaAtuacao = new javax.swing.JTextField();
        cxFuncao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cxDescricao = new javax.swing.JTextArea();
        btSelecionarLider = new javax.swing.JButton();
        btSelecionarMembros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rotAreaAtuacao.setText("Área da atuação:");

        rotDescricao.setText("Descrição:");

        rotFuncao.setText("Função:");

        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        cxAreaAtuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxAreaAtuacaoActionPerformed(evt);
            }
        });

        cxDescricao.setColumns(20);
        cxDescricao.setRows(5);
        jScrollPane1.setViewportView(cxDescricao);

        btSelecionarLider.setText("Selecionar líder...");
        btSelecionarLider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarLiderActionPerformed(evt);
            }
        });

        btSelecionarMembros.setText("Selecionar membros...");
        btSelecionarMembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarMembrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEnviar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rotDescricao)
                            .addComponent(rotFuncao)
                            .addComponent(rotAreaAtuacao)
                            .addComponent(jScrollPane1)
                            .addComponent(cxAreaAtuacao)
                            .addComponent(cxFuncao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btSelecionarLider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSelecionarMembros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(rotAreaAtuacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxAreaAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSelecionarLider))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSelecionarMembros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotFuncao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEnviar)
                    .addComponent(btLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxAreaAtuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxAreaAtuacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxAreaAtuacaoActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        LocalDate localDate = LocalDate.now();
        Date dataCriacao = Date.valueOf(localDate);
        Equipe equipe;
        Usuario liderEquipe = new Usuario();
        liderEquipe.setIdUsuario(guiController.getIdUsuario());
        List<Usuario> equipeMembros = guiController.getEquipeMembros();
        
        List<Integer> idMembros = new ArrayList<>();
        
        for (Usuario m : equipeMembros) {
            idMembros.add(m.getIdUsuario());
        }
        
        

        
        if(!idMembros.contains(liderEquipe.getIdUsuario())){
            equipeMembros.add(liderEquipe);
        }
        // adicionar projeto pelo controller depois

        try{
            String areaAtuacao = cxAreaAtuacao.getText();
            String descricao = cxDescricao.getText();
            String funcao = cxFuncao.getText();
            equipe = new Equipe(null, liderEquipe, areaAtuacao, descricao, funcao, projeto, equipeMembros, null);

            EquipeCtrl equipeDAO = new EquipeCtrl();
            equipeDAO.adicionar(equipe);
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,
                "Formato de valor inválido",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null,
                "Formato de valor inválido",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btEnviarActionPerformed

    private void btSelecionarLiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarLiderActionPerformed
        guiController.mostrarProjetoSelecionarUsuarioGUI(projeto.getIdProjeto());
    }//GEN-LAST:event_btSelecionarLiderActionPerformed

    private void btSelecionarMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarMembrosActionPerformed
        guiController.mostrarEquipeSelecionarUsuarioGUI(projeto.getIdProjeto());
    }//GEN-LAST:event_btSelecionarMembrosActionPerformed



    private void limpar() {
        cxAreaAtuacao.setText("");
        cxDescricao.setText("");
        cxFuncao.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSelecionarLider;
    private javax.swing.JButton btSelecionarMembros;
    private javax.swing.JTextField cxAreaAtuacao;
    private javax.swing.JTextArea cxDescricao;
    private javax.swing.JTextField cxFuncao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rotAreaAtuacao;
    private javax.swing.JLabel rotDescricao;
    private javax.swing.JLabel rotFuncao;
    // End of variables declaration//GEN-END:variables
}
