/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.GUIController;
import control.PerfilCtrl;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import model.Perfil;
import model.Usuario;

/**
 *
 * @author Fabio
 */
public class PerfilView extends javax.swing.JFrame {
    private Usuario usuarioSessao;
    private GUIController guiController;

    public Usuario getUsuarioSessao() {
        return usuarioSessao;
    }

    public void setUsuarioSessao(Usuario usuarioSessao) {
        this.usuarioSessao = usuarioSessao;
    }
    
    
    
    /**
     * Creates new form PerfilView
     */
    public PerfilView(GUIController guiController) {
        this.guiController = guiController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotNome = new javax.swing.JLabel();
        rotFuncao = new javax.swing.JLabel();
        rotDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cxTextDescricao = new javax.swing.JTextArea();
        cxNome = new javax.swing.JTextField();
        cxFuncao = new javax.swing.JTextField();
        btEnviar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rotNome.setText("Nome de exibição:");

        rotFuncao.setText("Função:");

        rotDescricao.setText("Descrição:");

        cxTextDescricao.setColumns(20);
        cxTextDescricao.setRows(5);
        jScrollPane1.setViewportView(cxTextDescricao);

        cxFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxFuncaoActionPerformed(evt);
            }
        });

        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEnviar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotFuncao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rotDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotFuncao)
                    .addComponent(cxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rotDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEnviar)
                    .addComponent(btLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void cxFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxFuncaoActionPerformed

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        LocalDate localDate = LocalDate.now();
        Date dataCriacao = Date.valueOf(localDate);
        Perfil perfil;
        // adicionar projeto pelo controller depois

        try{
            String nome = cxNome.getText();
            String descricao = cxTextDescricao.getText();
            String objetivo = cxFuncao.getText();
            perfil = new Perfil(null, nome, descricao, objetivo, usuarioSessao);

            PerfilCtrl perfilDAO = new PerfilCtrl();
            perfilDAO.atualizar(usuarioSessao, perfil);
            perfilDAO.getConexao().getConn().close();
        }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,
                "Formato de valor inválido",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null,
                "Formato de valor inválido",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btEnviarActionPerformed

    
    

    private void limpar() {
        cxTextDescricao.setText("");
        cxNome.setText("");
        cxFuncao.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JTextField cxFuncao;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextArea cxTextDescricao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rotDescricao;
    private javax.swing.JLabel rotFuncao;
    private javax.swing.JLabel rotNome;
    // End of variables declaration//GEN-END:variables
}
