/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ProjetoCtrl;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Equipe;
import model.Projeto;
import model.Tarefa;
import model.Usuario;

/**
 *
 * @author Fabio
 */
public class ProjetoViewerGUI extends javax.swing.JFrame {
    
    private Projeto projeto;
    /**
     * Creates new form ProjetoManagerGUI
     */
    public ProjetoViewerGUI() {
        initComponents();
        
        // Fetch projects from database
        ProjetoCtrl projetoDAO = new ProjetoCtrl();
        List<Usuario> usuarios = projetoDAO.consultarMembros(2);

        // Add each project to the content panel
        for (Usuario usuario : usuarios) {
            pnlUsuarios.add(createUserBlock(usuario));
        }
        
        pnlUsuarios.revalidate();
        pnlUsuarios.repaint();
        
        List<Tarefa> tarefas = projetoDAO.consultarTarefas(2);

        // Add each project to the content panel
        for (Tarefa tarefa : tarefas) {
            pnlTarefas.add(createTaskBlock(tarefa));
        }
        
        pnlTarefas.revalidate();
        pnlTarefas.repaint();
        
        List<Equipe> equipes = projetoDAO.consultarEquipes(2);

        // Add each project to the content panel
        for (Equipe equipe : equipes) {
            pnlEquipes.add(createTeamBlock(equipe));
        }
        
        pnlEquipes.revalidate();
        pnlEquipes.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        rotTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        pnlScrlLista1 = new javax.swing.JScrollPane();
        pnlTarefas = new javax.swing.JPanel();
        rotTarefas = new javax.swing.JLabel();
        pnlScrlLista = new javax.swing.JScrollPane();
        pnlUsuarios = new javax.swing.JPanel();
        rotEquipes = new javax.swing.JLabel();
        pnlScrlLista2 = new javax.swing.JScrollPane();
        pnlEquipes = new javax.swing.JPanel();
        rotUsuarios = new javax.swing.JLabel();
        rotObjetivo = new javax.swing.JLabel();
        rotPrazo = new javax.swing.JLabel();
        rotDataCriacao = new javax.swing.JLabel();
        rotDescricao = new javax.swing.JLabel();
        rotNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rotTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        rotTitulo.setText("Tasky");

        pnlScrlLista1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        pnlScrlLista1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlTarefas.setLayout(new javax.swing.BoxLayout(pnlTarefas, javax.swing.BoxLayout.Y_AXIS));
        pnlScrlLista1.setViewportView(pnlTarefas);

        rotTarefas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rotTarefas.setText("Tarefas:");

        pnlScrlLista.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        pnlScrlLista.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlUsuarios.setLayout(new javax.swing.BoxLayout(pnlUsuarios, javax.swing.BoxLayout.Y_AXIS));
        pnlScrlLista.setViewportView(pnlUsuarios);

        rotEquipes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rotEquipes.setText("Equipes:");

        pnlScrlLista2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        pnlScrlLista2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlEquipes.setLayout(new javax.swing.BoxLayout(pnlEquipes, javax.swing.BoxLayout.Y_AXIS));
        pnlScrlLista2.setViewportView(pnlEquipes);

        rotUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rotUsuarios.setText("Usuarios:");

        rotObjetivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rotObjetivo.setText("Objetivo:");

        rotPrazo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rotPrazo.setText("Prazo:");

        rotDataCriacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rotDataCriacao.setText("Data de criação:");

        rotDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rotDescricao.setText("jLabel1");

        rotNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotNome.setText("Projeto:");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rotDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rotDataCriacao)
                    .addComponent(rotPrazo)
                    .addComponent(rotObjetivo)
                    .addComponent(rotNome, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotEquipes)
                    .addComponent(pnlScrlLista2, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlScrlLista1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotTarefas))
                        .addGap(57, 57, 57)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlScrlLista, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotUsuarios))))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlPrincipalLayout.createSequentialGroup()
                            .addComponent(rotUsuarios)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pnlScrlLista, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlPrincipalLayout.createSequentialGroup()
                            .addComponent(rotTarefas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pnlScrlLista1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(rotNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rotDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rotDataCriacao)
                        .addGap(18, 18, 18)
                        .addComponent(rotPrazo)
                        .addGap(18, 18, 18)
                        .addComponent(rotObjetivo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(rotEquipes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlScrlLista2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(rotTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rotTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoViewerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoViewerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoViewerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoViewerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoViewerGUI().setVisible(true);
            }
        });
    }

    private JPanel createUserBlock(Usuario usuario) {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panel.setBackground(Color.WHITE);
        panel.setPreferredSize(new Dimension(350, 100));
        panel.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        
        ProjetoCtrl projetoDAO = new ProjetoCtrl();

        JLabel rotNome = new JLabel("<html><i>" + usuario.getNome() + "</i></html>");
        rotNome.setFont(new Font("Arial", Font.BOLD, 16));

        JLabel rotPerfilNome = new JLabel("<html><i>" + usuario.getPerfilUsuario().getNome() + "</i></html>");
        rotPerfilNome.setFont(new Font("Arial", Font.PLAIN, 12));
        
        JLabel rotIdUsuario = new JLabel("<html><i>ID: " + usuario.getIdUsuario() + "</i></html>");
        rotIdUsuario.setFont(new Font("Arial", Font.BOLD, 16));
        
        JLabel rotLider;
        
        if(projetoDAO.verificarLider(usuario.getIdUsuario(), projeto.getIdProjeto())){
            rotLider = new JLabel("<html><i>Líder</i></html>");
        }
        else{
            rotLider = new JLabel("");
        }
        
        JButton btDetalhes = new JButton("Detalhes");
        btDetalhes.addActionListener(e -> JOptionPane.showMessageDialog(null, "Usuario: " + usuario.getNome()));

        JPanel pnlTexto = new JPanel(new GridLayout(2, 2));
        pnlTexto.setBackground(Color.WHITE);
        pnlTexto.add(rotNome);
        pnlTexto.add(rotPerfilNome);
        pnlTexto.add(rotIdUsuario);
        pnlTexto.add(rotLider);

        panel.add(pnlTexto, BorderLayout.CENTER);
        panel.add(btDetalhes, BorderLayout.EAST);

        return panel;
    }
    
    private JPanel createTaskBlock(Tarefa tarefa) {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panel.setBackground(Color.WHITE);
        panel.setPreferredSize(new Dimension(350, 100));
        panel.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));

        JLabel rotDescricao = new JLabel("<html><i>" + tarefa.getDescricao() + "</i></html>");
        rotDescricao.setFont(new Font("Arial", Font.BOLD, 16));

        JLabel rotPrioridade = new JLabel("<html><i> Prioridade: " + tarefa.getPrioridade() + "</i></html>");
        rotPrioridade.setFont(new Font("Arial", Font.PLAIN, 12));
        
        JLabel rotPrazo = new JLabel("<html><i> Prazo: " + tarefa.getPrazoEntrega().toString() + "</i></html>");
        rotPrioridade.setFont(new Font("Arial", Font.PLAIN, 12));

        JButton btDetalhes = new JButton("Detalhes");
        btDetalhes.addActionListener(e -> JOptionPane.showMessageDialog(null, "Tarefa: " + tarefa.getDescricao()));

        JPanel pnlTexto = new JPanel(new GridLayout(2, 2));
        pnlTexto.setBackground(Color.WHITE);
        pnlTexto.add(rotDescricao);
        pnlTexto.add(rotPrioridade);
        pnlTexto.add(rotPrazo);

        panel.add(pnlTexto, BorderLayout.CENTER);
        panel.add(btDetalhes, BorderLayout.EAST);

        return panel;
    }
    
    private JPanel createTeamBlock(Equipe equipe) {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panel.setBackground(Color.WHITE);
        panel.setPreferredSize(new Dimension(350, 100));
        panel.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));

        JLabel rotDescricao = new JLabel("<html><i>" + equipe.getDescricao() + "</i></html>");
        rotDescricao.setFont(new Font("Arial", Font.BOLD, 16));
        
        JLabel rotFuncao = new JLabel("<html><i> Função: " + equipe.getFuncao() + "</i></html>");
        rotFuncao.setFont(new Font("Arial", Font.PLAIN, 12));

        JButton btDetalhes = new JButton("Detalhes");
        btDetalhes.addActionListener(e -> JOptionPane.showMessageDialog(null, "Equipe: " + equipe.getDescricao()));

        JPanel pnlTexto = new JPanel(new GridLayout(2, 2));
        pnlTexto.setBackground(Color.WHITE);
        pnlTexto.add(rotDescricao);
        pnlTexto.add(rotFuncao);

        panel.add(pnlTexto, BorderLayout.CENTER);
        panel.add(btDetalhes, BorderLayout.EAST);

        return panel;
    }
    
    public void preencherDados(){
        rotNome.setText("<html><i>Projeto: " + projeto.getNome() + "</i></html>");
        rotDescricao.setText("<html><i>" + projeto.getDescricao() + "</i></html>");
        rotDataCriacao.setText("Data de criação: " + projeto.getDataCriacao().toString());
        rotPrazo.setText("Prazo: " + projeto.getDataUltima().toString());
        rotObjetivo.setText("Objetivo: " + projeto.getObjetivo());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlEquipes;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JScrollPane pnlScrlLista;
    private javax.swing.JScrollPane pnlScrlLista1;
    private javax.swing.JScrollPane pnlScrlLista2;
    private javax.swing.JPanel pnlTarefas;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JLabel rotDataCriacao;
    private javax.swing.JLabel rotDescricao;
    private javax.swing.JLabel rotEquipes;
    private javax.swing.JLabel rotNome;
    private javax.swing.JLabel rotObjetivo;
    private javax.swing.JLabel rotPrazo;
    private javax.swing.JLabel rotTarefas;
    private javax.swing.JLabel rotTitulo;
    private javax.swing.JLabel rotUsuarios;
    // End of variables declaration//GEN-END:variables
}
