/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.DateConverter;
import control.GUIController;
import control.ProjetoCtrl;
import control.TarefaAcademicaCtrl;
import control.TarefaCtrl;
import control.TarefaPessoalCtrl;
import control.TarefaTrabalhoCtrl;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import model.Equipe;
import model.Projeto;
import model.Tarefa;
import model.TarefaAcademica;
import model.TarefaPessoal;
import model.TarefaTrabalho;
import model.Usuario;

/**
 *
 * @author Fabio
 */
public class ProjetoAtribuirTarefaView extends javax.swing.JFrame {
    private Usuario usuarioSessao;
    private Projeto projeto;
    private GUIController guiController;
    /**
     * Creates new form TarefaView
     * @param guiController
     * @param idProjeto

     */
    public ProjetoAtribuirTarefaView(GUIController guiController, Integer idProjeto) {

        this.guiController = guiController;
        
        ProjetoCtrl projetoDAO = new ProjetoCtrl();
        projeto = projetoDAO.consultarProjeto(idProjeto);
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cxLocal = new javax.swing.JTextField();
        cxRecorrencia = new javax.swing.JTextField();
        rotLocal = new javax.swing.JLabel();
        rotRecorrencia = new javax.swing.JLabel();
        cxPrazoRevisao = new javax.swing.JTextField();
        cxDepartamento = new javax.swing.JTextField();
        rotPrazoRevisao = new javax.swing.JLabel();
        rotDepartamento = new javax.swing.JLabel();
        cxNota = new javax.swing.JTextField();
        rotNota = new javax.swing.JLabel();
        cxMateria = new javax.swing.JTextField();
        cxProfessor = new javax.swing.JTextField();
        rotProfessor = new javax.swing.JLabel();
        rotMateria = new javax.swing.JLabel();
        rotTitulo = new javax.swing.JLabel();
        rotDescricao = new javax.swing.JLabel();
        rotPrazo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cxDescricao = new javax.swing.JTextArea();
        cxPrazoEntrega = new javax.swing.JTextField();
        rotPrioridade = new javax.swing.JLabel();
        ComboBoxPrioridade = new javax.swing.JComboBox<>();
        btEnviar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSelecionarUsuario = new javax.swing.JButton();
        pnlTipo = new javax.swing.JPanel();
        rotTipo = new javax.swing.JLabel();
        comboBoxTipo = new javax.swing.JComboBox<>();
        btSelecionarEquipe = new javax.swing.JButton();

        rotLocal.setText("Local:");

        rotRecorrencia.setText("Recorrencia:");

        cxPrazoRevisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPrazoRevisaoActionPerformed(evt);
            }
        });

        rotPrazoRevisao.setText("Prazo de revisão:");

        rotDepartamento.setText("Departamento:");

        cxNota.setToolTipText("");

        rotNota.setText("Nota:");

        cxProfessor.setMaximumSize(new java.awt.Dimension(100, 5));

        rotProfessor.setText("Professor:");

        rotMateria.setText("Materia:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rotTitulo.setText("Tarefa:");

        rotDescricao.setText("Descrição:");

        rotPrazo.setText("Prazo de entrega:");

        cxDescricao.setColumns(20);
        cxDescricao.setRows(5);
        jScrollPane1.setViewportView(cxDescricao);

        rotPrioridade.setText("Prioridade:");

        ComboBoxPrioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixa", "Média", "Alta", "Urgente" }));
        ComboBoxPrioridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxPrioridadeActionPerformed(evt);
            }
        });

        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSelecionarUsuario.setText("Selecionar Usuario...");
        btSelecionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarUsuarioActionPerformed(evt);
            }
        });

        pnlTipo.setLayout(new java.awt.GridLayout(3, 2, 10, 5));

        rotTipo.setText("Tipo:");

        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genérico", "Acadêmica", "Pessoal", "Trabalho" }));
        comboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoActionPerformed(evt);
            }
        });

        btSelecionarEquipe.setText("Selecionar Equipe...");
        btSelecionarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarEquipeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotTitulo)
                            .addComponent(rotPrazo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rotPrioridade)
                                    .addComponent(ComboBoxPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rotTipo)
                                    .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotDescricao)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cxPrazoEntrega)
                                    .addGap(19, 19, 19)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btSelecionarUsuario)
                                        .addComponent(btSelecionarEquipe)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(pnlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEnviar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rotTitulo)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotPrazo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxPrazoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSelecionarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btSelecionarEquipe)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotPrioridade)
                    .addComponent(rotTipo))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEnviar)
                    .addComponent(btLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxPrioridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxPrioridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxPrioridadeActionPerformed

    private void comboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoActionPerformed
        String opc = (String) comboBoxTipo.getSelectedItem();
        
        if(opc.equals("Genérico")){
            mostrarEditorGenerico();
        }
        if(opc.equals("Acadêmica")){
            mostrarEditorAcademico();
        } 
        if(opc.equals("Pessoal")){
            mostrarEditorPessoal();
        } 
        if(opc.equals("Trabalho")){
            mostrarEditorTrabalho();
        } 
    }//GEN-LAST:event_comboBoxTipoActionPerformed

    private void cxPrazoRevisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPrazoRevisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPrazoRevisaoActionPerformed

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        String opc = (String) comboBoxTipo.getSelectedItem();
        Tarefa tarefa;
        LocalDate localDate = LocalDate.now();
        Date dataCriacao = Date.valueOf(localDate);
        
        Equipe equipe = new Equipe(); // adicionar equipe pelo controller
        equipe.setIdEquipe(guiController.getIdEquipe());
        
        Usuario usuario = new Usuario();
        usuario.setIdUsuario(guiController.getIdUsuario());
        if(opc.equals("Genérico")){
            
            try{
                Date prazoEntrega = DateConverter.convertToSqlDate(cxPrazoEntrega.getText());
                String descricao = cxDescricao.getText();
                String prioridade = (String) ComboBoxPrioridade.getSelectedItem();
                tarefa = new Tarefa(0, prazoEntrega, descricao, prioridade, dataCriacao, usuario, equipe, projeto);
                TarefaCtrl tarefaDAO = new TarefaCtrl();
                tarefaDAO.adicionar(tarefa);
            }
            catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,
                "Formato de valor inválido",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,
                "Formato de valor inválido",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            }
        }
        if(opc.equals("Acadêmica")){
            
            try{
                Date prazoEntrega = DateConverter.convertToSqlDate(cxPrazoEntrega.getText());
                String descricao = cxDescricao.getText();
                String prioridade = (String) ComboBoxPrioridade.getSelectedItem();
                String materia = cxMateria.getText();
                String professor = cxProfessor.getText();
                double nota = Double.parseDouble(cxNota.getText());
                TarefaAcademica tarefaAcademica = new TarefaAcademica(0, prazoEntrega, descricao, prioridade, dataCriacao, usuario, equipe, projeto, materia, professor, nota);
                TarefaAcademicaCtrl tarefaAcademicaDAO = new TarefaAcademicaCtrl();
                tarefaAcademicaDAO.adicionar(tarefaAcademica);
            }
            catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,
                "Formato de valor inválido",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,
                "Formato de valor inválido",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            }
        } 
        if(opc.equals("Pessoal")){

            
            try{
                Date prazoEntrega = DateConverter.convertToSqlDate(cxPrazoEntrega.getText());
                String descricao = cxDescricao.getText();
                String prioridade = (String) ComboBoxPrioridade.getSelectedItem();
                String recorrencia = cxRecorrencia.getText();
                String local = cxLocal.getText();
                
                TarefaPessoal tarefaPessoal = new TarefaPessoal(0, prazoEntrega, descricao, prioridade, dataCriacao, usuario, equipe, projeto, recorrencia, local);
                TarefaPessoalCtrl tarefaPessoalDAO = new TarefaPessoalCtrl();
                tarefaPessoalDAO.adicionar(tarefaPessoal);
            }
            catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,
                "Formato de valor inválido",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,
                "Formato de valor inválido",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            }
        } 
        if(opc.equals("Trabalho")){

            try{
                Date prazoEntrega = DateConverter.convertToSqlDate(cxPrazoEntrega.getText());
                String descricao = cxDescricao.getText();
                String prioridade = (String) ComboBoxPrioridade.getSelectedItem();
                String departamento = cxDepartamento.getText();
                Date prazoRevisao = DateConverter.convertToSqlDate(cxPrazoRevisao.getText());
                
                TarefaTrabalho tarefaTrabalho = new TarefaTrabalho(0, prazoEntrega, descricao, prioridade, dataCriacao, usuarioSessao, equipe, projeto, departamento, prazoRevisao);
                TarefaTrabalhoCtrl tarefaTrabalhoDAO = new TarefaTrabalhoCtrl();
                tarefaTrabalhoDAO.adicionar(tarefaTrabalho);
            }
            catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,
                "Formato de valor inválido",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,
                "Formato de valor inválido",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            }
        } 
    }//GEN-LAST:event_btEnviarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSelecionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarUsuarioActionPerformed
        guiController.mostrarProjetoSelecionarUsuarioGUI(projeto.getIdProjeto());
        
    }//GEN-LAST:event_btSelecionarUsuarioActionPerformed

    private void btSelecionarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarEquipeActionPerformed
        guiController.mostrarProjetoSelecionarEquipeGUI(projeto.getIdProjeto());
    }//GEN-LAST:event_btSelecionarEquipeActionPerformed


    public void mostrarEditorGenerico(){
        pnlTipo.removeAll();
        
        pnlTipo.revalidate();
        pnlTipo.repaint(); 
    }
    
    public void mostrarEditorAcademico(){
        pnlTipo.removeAll();
        
        pnlTipo.add(rotMateria);
        pnlTipo.add(rotProfessor);
        pnlTipo.add(cxMateria);
        pnlTipo.add(cxProfessor);
        pnlTipo.add(rotNota);
        pnlTipo.add(cxNota);
        
        
        
        pnlTipo.revalidate();
        pnlTipo.repaint(); 
    }
    
    public void mostrarEditorPessoal(){
        pnlTipo.removeAll();
        
        pnlTipo.add(rotRecorrencia);
        pnlTipo.add(rotLocal);
        pnlTipo.add(cxRecorrencia);
        pnlTipo.add(cxLocal);
        
        pnlTipo.revalidate();
        pnlTipo.repaint(); 
    }
    
    public void mostrarEditorTrabalho(){
        pnlTipo.removeAll();
        
        pnlTipo.add(rotDepartamento);
        pnlTipo.add(rotPrazoRevisao);
        pnlTipo.add(cxDepartamento);
        pnlTipo.add(cxPrazoRevisao);
        
        pnlTipo.revalidate();
        pnlTipo.repaint(); 
    }
    
    private void limpar() {
        cxDepartamento.setText("");
        cxLocal.setText("");
        cxMateria.setText("");
        cxNota.setText("");
        cxPrazoEntrega.setText("");
        cxPrazoRevisao.setText("");
        cxProfessor.setText("");
        cxRecorrencia.setText("");
        cxDescricao.setText("");
    }

    public Usuario getUsuarioSessao() {
        return usuarioSessao;
    }

    public void setUsuarioSessao(Usuario usuarioSessao) {
        this.usuarioSessao = usuarioSessao;
    }

    public Projeto getProjeto() {
        return projeto;
    }

    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxPrioridade;
    private javax.swing.JButton btEnviar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSelecionarEquipe;
    private javax.swing.JButton btSelecionarUsuario;
    private javax.swing.JComboBox<String> comboBoxTipo;
    private javax.swing.JTextField cxDepartamento;
    private javax.swing.JTextArea cxDescricao;
    private javax.swing.JTextField cxLocal;
    private javax.swing.JTextField cxMateria;
    private javax.swing.JTextField cxNota;
    private javax.swing.JTextField cxPrazoEntrega;
    private javax.swing.JTextField cxPrazoRevisao;
    private javax.swing.JTextField cxProfessor;
    private javax.swing.JTextField cxRecorrencia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlTipo;
    private javax.swing.JLabel rotDepartamento;
    private javax.swing.JLabel rotDescricao;
    private javax.swing.JLabel rotLocal;
    private javax.swing.JLabel rotMateria;
    private javax.swing.JLabel rotNota;
    private javax.swing.JLabel rotPrazo;
    private javax.swing.JLabel rotPrazoRevisao;
    private javax.swing.JLabel rotPrioridade;
    private javax.swing.JLabel rotProfessor;
    private javax.swing.JLabel rotRecorrencia;
    private javax.swing.JLabel rotTipo;
    private javax.swing.JLabel rotTitulo;
    // End of variables declaration//GEN-END:variables
}
